/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Pathless_layoutRouteImport } from './routes/_pathless_layout'
import { Route as Pathless_layoutIndexRouteImport } from './routes/_pathless_layout/index'
import { Route as Pathless_layoutNested_layoutRouteImport } from './routes/_pathless_layout/_nested_layout'
import { Route as Pathless_layoutNested_layoutNested_pathRouteImport } from './routes/_pathless_layout/_nested_layout/nested_path'

const Pathless_layoutRoute = Pathless_layoutRouteImport.update({
  id: '/_pathless_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const Pathless_layoutIndexRoute = Pathless_layoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Pathless_layoutRoute,
} as any)
const Pathless_layoutNested_layoutRoute =
  Pathless_layoutNested_layoutRouteImport.update({
    id: '/_nested_layout',
    getParentRoute: () => Pathless_layoutRoute,
  } as any)
const Pathless_layoutNested_layoutNested_pathRoute =
  Pathless_layoutNested_layoutNested_pathRouteImport.update({
    id: '/nested_path',
    path: '/nested_path',
    getParentRoute: () => Pathless_layoutNested_layoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof Pathless_layoutIndexRoute
  '/nested_path': typeof Pathless_layoutNested_layoutNested_pathRoute
}
export interface FileRoutesByTo {
  '/': typeof Pathless_layoutIndexRoute
  '/nested_path': typeof Pathless_layoutNested_layoutNested_pathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_pathless_layout': typeof Pathless_layoutRouteWithChildren
  '/_pathless_layout/_nested_layout': typeof Pathless_layoutNested_layoutRouteWithChildren
  '/_pathless_layout/': typeof Pathless_layoutIndexRoute
  '/_pathless_layout/_nested_layout/nested_path': typeof Pathless_layoutNested_layoutNested_pathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nested_path'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nested_path'
  id:
    | '__root__'
    | '/_pathless_layout'
    | '/_pathless_layout/_nested_layout'
    | '/_pathless_layout/'
    | '/_pathless_layout/_nested_layout/nested_path'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Pathless_layoutRoute: typeof Pathless_layoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pathless_layout': {
      id: '/_pathless_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof Pathless_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathless_layout/': {
      id: '/_pathless_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof Pathless_layoutIndexRouteImport
      parentRoute: typeof Pathless_layoutRoute
    }
    '/_pathless_layout/_nested_layout': {
      id: '/_pathless_layout/_nested_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof Pathless_layoutNested_layoutRouteImport
      parentRoute: typeof Pathless_layoutRoute
    }
    '/_pathless_layout/_nested_layout/nested_path': {
      id: '/_pathless_layout/_nested_layout/nested_path'
      path: '/nested_path'
      fullPath: '/nested_path'
      preLoaderRoute: typeof Pathless_layoutNested_layoutNested_pathRouteImport
      parentRoute: typeof Pathless_layoutNested_layoutRoute
    }
  }
}

interface Pathless_layoutNested_layoutRouteChildren {
  Pathless_layoutNested_layoutNested_pathRoute: typeof Pathless_layoutNested_layoutNested_pathRoute
}

const Pathless_layoutNested_layoutRouteChildren: Pathless_layoutNested_layoutRouteChildren =
  {
    Pathless_layoutNested_layoutNested_pathRoute:
      Pathless_layoutNested_layoutNested_pathRoute,
  }

const Pathless_layoutNested_layoutRouteWithChildren =
  Pathless_layoutNested_layoutRoute._addFileChildren(
    Pathless_layoutNested_layoutRouteChildren,
  )

interface Pathless_layoutRouteChildren {
  Pathless_layoutNested_layoutRoute: typeof Pathless_layoutNested_layoutRouteWithChildren
  Pathless_layoutIndexRoute: typeof Pathless_layoutIndexRoute
}

const Pathless_layoutRouteChildren: Pathless_layoutRouteChildren = {
  Pathless_layoutNested_layoutRoute:
    Pathless_layoutNested_layoutRouteWithChildren,
  Pathless_layoutIndexRoute: Pathless_layoutIndexRoute,
}

const Pathless_layoutRouteWithChildren = Pathless_layoutRoute._addFileChildren(
  Pathless_layoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  Pathless_layoutRoute: Pathless_layoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
